### PR TITLE
Switch to xterm.js

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
cc @spadgett 

still need to figure out why it doesn't seem to be honoring cols correctly

**Comment by jwforres** [comment]
xterm.js switches to a model that has a visible scrollbar when there is content in the scrollback, for the browsers that support it we should style the scrollbar colors to look better with the black background

terminal-updates

**Comment by jwforres** [comment]
@stefwalter do you have concerns about the visible scrollbar in general https://github.com/kubernetes-ui/container-terminal/pull/25#issuecomment-314481706

There a lot of things about the xterm behavior (plus long term support) that seem better at this point, so I think we definitely want to switch to it for openshift but I don't want to break things for cockpit.  If necessary we will fork container-terminal and use our own version based on xterm.  Let me know.

**Comment by jwforres** [comment]
cc @rhamilto or @sg00dwin this is the PR for the xterm changes, if you want to play with the scrollbar colors to find something that looks good

**Comment by rhamilto** [comment]
> cc @rhamilto or @sg00dwin this is the PR for the xterm changes, if you want to play with the scrollbar colors to find something that looks good

I'll take a look

**Comment by stefwalter** [comment]
> There a lot of things about the xterm behavior (plus long term support) that seem better at this point, so I think we definitely want to switch to it for openshift but I don't want to break things for cockpit. If necessary we will fork container-terminal and use our own version based on xterm. Let me know.

I think xterm is the right way forward. Lets not fork. We pull a specific older version of container-terminal, but would update to this soon.

**Comment by stefwalter** [comment]
FYI @petervo

**Comment by jwforres** [comment]
We'll cut a major version (2.0) when we release this since its a big underlying change

**Comment by jwforres** [comment]
Seeing weird scrollback behavior with the keyboard in applications like vi and less, partially improved by setting applicationCursor:true  remaining issue seems to only happen if you arrow down a couple times and then arrow ALL the way back to the top, then the scrollback buffer isnt getting cleared out.  If you arrow back only part way then the scrollback seems to contain the content you would expect.

**Comment by stefwalter** [comment]
Just wanted to note: After we merge this, we should bump the Y number of the package, as this is more than just a micro update. Thanks for the effort here.

**Comment by jwforres** [comment]
The remaining issue is minor relative to the benefits we gain, its being tracked upstream at https://github.com/sourcelair/xterm.js/issues/802  would propose merging this, @spadgett ?

**Comment by spadgett** [comment]
+1 -- I don't think that issue should block us from going ahead. This fixes a lot more problems than it introduces

**Pull request merged**
