### PR TITLE
Version 2.1.0

### PR DESCRIPTION
**Pull request by spadgett**
* Bump xterm.js to 2.9.0
* Add dependencies stanza to package.json

https://github.com/sourcelair/xterm.js/releases/tag/2.9.0

@petervo PTAL
@stefwalter CC

### CODE REVIEW

**Comment by spadgett** [comment]
@petervo ping

**Comment by spadgett** [comment]
@petervo @stefwalter Any objections to this? Waiting on a review.

**Comment by petervo** [comment]
I'm ok with this, we are not ready on the cockpit side for this move yet. But that doesn't need to block this.

**Comment by spadgett** [comment]
Thanks @petervo

**Pull request merged**
