### PR TITLE
Bump version to 2.0.2

### PR DESCRIPTION
**Pull request by spadgett**
@petervo @stefwalter

### CODE REVIEW

**Comment by petervo** [comment]
Can we bump the package.json version as well? Maybe the changes from https://github.com/kubernetes-ui/container-terminal/pull/23 would be good to include as well.

**Comment by spadgett** [comment]
I was going to, but didn't see a version in package.json

**Comment by petervo** [comment]
I think that's what #23 was adding

**Comment by spadgett** [comment]
I don't mind adding it. @petervo were you saying to add those changes to this PR or wait until #23 merges? Would be good to cut a release so that we can pick up the fix in #28.

@stefwalter Any preference?

**Comment by petervo** [comment]
Either way works for me. I just don't have perms to merge anything, that's why I'm bringing it up

**Comment by spadgett** [comment]
@petervo OK pulled in the package.json changes from #23

**Comment by petervo** [comment]
LGTM

**Comment by stefwalter** [comment]
I gave both @petervo and @spadgett access to the NPM package

**Pull request merged**
