### PR TITLE
Autofocus the terminal after the connection is established

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
@stefwalter any concern with this change?  it fixes it so you don't have to actually click into the terminal after the connection is established.  I can make this an option if you use this somewhere where you wouldn't want the autofocus behavior?

cc @spadgett

**Comment by stefwalter** [comment]
>  I can make this an option if you use this somewhere where you wouldn't want the autofocus behavior?

I think that would be good. There is the case where multiple terminals are shown on a page, and this will race between them rather unpredictably.

**Comment by jwforres** [comment]
@stefwalter updated to make autofocus an option, and setting autofocus in the index.html sample

**Comment by stefwalter** [comment]
Nice. Merged. I still have issues with focus happening unexpectedly, but that's independent of this pull request.

**Pull request merged**
