### PR TITLE
Handle unicode characters

### PR DESCRIPTION
**Pull request by spadgett**
Correctly encode and decode unicode characters. See notes on unicode strings here:

https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/btoa

@stefwalter PTAL
@jwforres @csrwng CC

### CODE REVIEW

**Comment by spadgett** [comment]
Before (left) and after (right)

openshift_web_console_and_openshift_web_console

**Comment by jwforres** [comment]
@spadgett this is the old bugzilla i mentioned https://bugzilla.redhat.com/show_bug.cgi?id=1292507

**Comment by stefwalter** [comment]
Nice. Merged.

**Comment by spadgett** [comment]
@stefwalter Thanks! 👍  Do you mind cutting a release?

**Pull request closed without merging**
